spring:
  application:
    name: employee-consumer

server:
  port: 8082
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  metrics:
    enabled: true
  circuitbreaker:
    enabled: true
  okhttp:
    enabled: true
#  client:
#    config:
#      employee-producer:
#        metrics.enable: true
#        loggerLevel: full
#        retryer: com.example.employeeconsumer.config.CustomRetryer
#        errorDecoder: com.example.employeeconsumer.config.SampleErrorDecode
#        capabilities:
#          - feign.micrometer.MicrometerCapability
logging:
  level:
    root: INFO
    web: ERROR
    org:
      springframework:
        web: ERROR
        security: ERROR
        data: ERROR
    com:
      example:
        employeeconsumer:
          client:
            EmployeeClient: DEBUG
