apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: student-client
  name: student-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: student-client
    spec:
      containers:
      - image: pcdinh/kube-demo-client:latest
        name: kube-demo-client
        resources: {}
status: {}
