apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: develop
  name: namespace-reader-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: namespace-reader-role-binding
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-reader-role
subjects:
  - kind: ServiceAccount
    name: demoappserviceaccount
    namespace: develop
